export default {
  startupFocus: true,
  toolbarCanCollapse: false,
  toolbar: 'instructor_notes',
  toolbar_instructor_notes:
    [
      { name: 'clipboard', items: ['Cut', 'Copy', 'Paste', 'Undo', 'Redo'] },
      { name: 'basicstyles', items: ['Bold', 'Italic', 'Underline', 'Superscript'] },
      { name: 'paragraph',
        items: [
          'NumberedList',
          'BulletedList',
          '-',
          'Outdent',
          'Indent',
          'JustifyLeft',
          'JustifyCenter',
          'JustifyRight',
          'JustifyBlock',
          'SpecialChar',
        ],
      },
      '/',
      { name: 'styles', items: ['Font', 'FontSize'] },
      { name: 'colors', items: ['TextColor', 'BGColor'] },
    ],
  resize_enabled: true,
  resize_maxWidth: '387px',
  resize_minWidth: '387px',
  removePlugins: 'elementspath',
  uiColor: '#E5E5E5',
  height: '100px',
  width: '387px',
};
