namespace :languages do
  desc 'Generate accent bar characters in JSON format'
  task :generate_accent_bar_js do
    language_accents = YAML.load_file(Rails.root.join('config', 'accent_bar_characters.yml'))
    pretty_json = JSON.pretty_generate(language_accents)
    File.open(File.join('app', 'javascript', 'src', 'shared', 'accent_bar_characters.js'), 'w') do |f|
      f.write("/**\n")
      f.write(" * @fileoverview\n")
      f.write(" * NOTE: This file is generated by a rake task, do not edit by hand.\n")
      f.write(" */\n")
      f.write("\n")
      f.write("const languages = #{pretty_json}\n")
      f.write("\n")
      f.write("export languages;\n")
    end
  end
end
