feature 'DashboardAnnouncements', js: true, chrome: true do
  include RspecJsCommonHelpers
  include RspecJsApiHelpers

  let(:user) { create(:user) }

  def expect_flash(type, message)
    flash = find(".test-flash-#{type}")
    expect(flash).to be_visible
    expect(flash).to have_text(message)
  end

  def click_modal
    within('.test-change-platform') do
      click_button('Change announcement')
    end
  end

  def create_announcement_selector(announcement_id)
    "test-announcement-#{announcement_id}"
  end

  def expect_page_to_display_announcement(announcement_id, title, body, url, link_text)
    within(".test-announcement-#{announcement_id}") do
      expect(page).to have_text(title)
      expect(page).to have_text(body)
      expect(page).to have_link(link_text, href: url)
      expect(page).to have_link('edit')
      expect(page).to have_link('delete')
    end
  end

  before do
    user.roles << Role.create!(name: Role::ANNOUNCEMENT_CREATOR)
    initialize_client_calls_for_user(user)
    log_in_as(user)
  end

  scenario 'As an announcement creator, I can create different dashboard announcements' do
    no_announcement_message = 'There are no instructor dashboard announcements'
    save_button_label = 'Save'
    cancel_button_label = 'cancel'
    create_announcement = 'Create announcement'
    edit_announcement = 'edit'
    original_title = 'Original Title'
    edited_title = 'Edited Title'
    title_field_label = 'Title'
    body_field_label = 'Announcement text'
    url_field_label = 'URL'
    link_text_field_label = 'Link text'
    announcement_id = ''
    original_announcement_text = 'Original Announcement'
    edited_announcement_text = 'Edited Announcement'
    original_url = 'http://help.vhlcentral.com'
    edited_url = 'http://otherhelp.vhlcentral.com'
    original_link_text = 'Click me'
    edited_link_text = 'Different link text message'
    supersite = 'Supersite'

    purpose 'I can navigate to the dashboard announcements index page' do
      visit dashboard_announcements_path
      step 'The dashboard announcements index page displays no announcement' do
        expect(page).to have_text(no_announcement_message)
      end
    end

    purpose 'When creating a dashboard announcement I can cancel the procedure' do
      step 'Click on the link to create a new dashboard announcement' do
        expect(page).to have_link(create_announcement)
        click_link(create_announcement)
      end
      step 'Add a title' do
        fill_in(title_field_label, with: original_title)
      end
      step 'Click on the cancel button' do
        # We are not searching for the text of the 'cancel' alerts
        # They are generated by the <% enable_unsaved_changes_protection %>
        # For some reason, Capybara does not find the text in these cases
        if ENV['NO_CHROME_UNLOAD'] == 'true'
          click_link(cancel_button_label)
        else
          accept_alert do
            click_link(cancel_button_label)
          end
        end
      end
      step 'The dashboard announcements index page displays no announcement' do
        expect(page).to have_no_text(original_announcement_text)
      end
    end

    purpose 'When creating a dashboard announcement a title, message and VOL or SS is required' do
      step 'Click on the link to create a new announcement' do
        click_link(create_announcement)
      end
      step 'Click on the save button' do
        click_button(save_button_label)
      end
      step 'I see an error message saying that a title, body and URL is required' do
        expect(page).to have_selector(
          '.c-message--error .c-message__body',
          text: 'There were problems with the following 5 fields:'
        )
        expect(page.all('.c-message--error li').map(&:text)).to contain_exactly(
          'Title is required',
          'Body is required',
          'Link text is required',
          'External url is required',
          'External url is invalid'
        )
      end
      step 'I see a flash notice that the announcement has not saved' do
        expect_flash(:error, 'Could not create the announcement')
      end
    end

    purpose 'When creating a dashboard announcement with valid values, it is saved' do
      step 'Check the SS checkbox' do
        vhl_check(supersite, allow_label_click: true)
      end
      step 'Fill in the title field' do
        fill_in(title_field_label, with: original_title)
      end
      step 'Fill in the message field' do
        fill_in(body_field_label, with: original_announcement_text)
      end
      step 'Fill in the URL' do
        fill_in(url_field_label, with: original_url)
      end
      step 'Fill in the link text' do
        fill_in(link_text_field_label, with: 'Click me')
      end
      step 'Click on the save button' do
        click_button(save_button_label)
      end
      step 'I see a success message' do
        expect_flash(:notice, 'The announcement was successfully created')
      end
      announcement_id = DashboardAnnouncement.last.id
      step 'The dashboard announcements index page displays the announcement' do
        expect_page_to_display_announcement(announcement_id,
                                            original_title,
                                            original_announcement_text,
                                            original_url,
                                            original_link_text)
      end
    end

    purpose 'When creating a dashboard announcement I can update fields' do
      announcement_id = DashboardAnnouncement.last.id
      step 'Click on the edit button of the announcement' do
        within(".test-announcement-#{announcement_id}") do
          click_link('edit')
        end
      end
      step 'The title is set to the value I previously chose' do
        expect(page).to have_field(title_field_label, with: original_title)
      end
      step 'The message is set to the value I previously chose' do
        expect(page).to have_field(body_field_label, with: original_announcement_text)
      end
      step 'Set a new title, message, url and message' do
        fill_in(title_field_label, with: edited_title)
        fill_in(body_field_label, with: edited_announcement_text)
        fill_in(url_field_label, with: edited_url)
        fill_in(link_text_field_label, with: edited_link_text)
      end
      step 'Click on the save button' do
        click_button(save_button_label)
      end
      click_modal
      step 'I see a success message' do
        expect_flash(:notice, 'The announcement was successfully modified')
      end
      step 'The dashboard announcements index page displays the announcement correctly' do
        expect_page_to_display_announcement(
          announcement_id,
          edited_title,
          edited_announcement_text,
          edited_url,
          edited_link_text
        )
      end
    end

    purpose 'When creating a dashboard announcement, an invalid URL is not permitted' do
      step 'Click on the create button' do
        click_link(create_announcement)
      end
      step 'Fill in fields' do
        fill_in(title_field_label, with: original_title)
        fill_in(body_field_label, with: original_announcement_text)
        fill_in(link_text_field_label, with: original_link_text)
        fill_in(url_field_label, with: 'This is not a url')
      end
      step 'Click on the save button' do
        click_button(save_button_label)
      end
      step 'Expect to see an error message' do
        expect(page).to have_selector(
          '.c-message--error .c-message__body',
          text: 'There were problems with the following 1 field:'
        )
        expect(page.all('.c-message--error li').map(&:text)).to contain_exactly(
          'External url is invalid'
        )
        expect_flash(:error, 'Could not create the announcement')
      end
    end

    purpose 'When editing a dashboard announcement I can cancel the procedure' do
      step 'Click on the edit button of the announcement' do
        visit(dashboard_announcements_path)
        click_link(edit_announcement)
      end
      step 'Set a new title' do
        fill_in(title_field_label, with: original_title)
      end
      step 'Click on the cancel button' do
        if ENV['NO_CHROME_UNLOAD'] == 'true'
          click_link(cancel_button_label)
        else
          accept_alert do
            click_link(cancel_button_label)
          end
        end
      end
      step 'The dashboard announcement index page displays the previously saved announcement' do
        expect_page_to_display_announcement(announcement_id,
                                            edited_title,
                                            edited_announcement_text,
                                            edited_url,
                                            edited_link_text)
      end
    end

    purpose 'When editing a dashboard announcement, I see an error message if it is missing data' do
      step 'Click on the link to create a new announcement' do
        click_link(edit_announcement)
      end
      step 'Remove title' do
        fill_in(title_field_label, with: '')
      end
      step 'Click on the save button' do
        click_button(save_button_label)
      end
      step 'Accept alert' do
        click_modal
      end
      step 'I see a flash notice that the announcement has not saved' do
        expect_flash(:error, 'Could not modify the announcement')
      end
      step 'I see an error message saying that a title is required' do
        expect(page).to have_selector(
          '.c-message--error .c-message__body',
          text: 'There were problems with the following 1 field:'
        )
        expect(page.all('.c-message--error li').map(&:text)).to contain_exactly(
          'Title is required'
        )
        expect_flash(:error, 'Could not modify the announcement')
      end
      step 'Return to the index page' do
        click_link(cancel_button_label)
      end
    end

    purpose 'I can only have one visible announcement per program type' do
      DashboardAnnouncement.last.update(vol: true, supersite: true)
      visit dashboard_announcements_path
      step 'I see a warning that there is already a visible announcement' do
        click_link(create_announcement)
        fill_in(title_field_label, with: original_title)
        fill_in(body_field_label, with: original_announcement_text)
        fill_in(link_text_field_label, with: original_link_text)
        fill_in(url_field_label, with: original_url)
        vhl_check(supersite, allow_label_click: true)
        click_button(save_button_label)
        click_modal
      end
      new_announcement_id = DashboardAnnouncement.last.id
      step 'The expected announcement is now visible' do
        expect_page_to_display_announcement(new_announcement_id,
                                            original_title,
                                            original_announcement_text,
                                            original_url,
                                            original_link_text)
      end
    end

    purpose 'I can delete a dashboard announcement' do
      step 'An alert with text "Are you sure you want to delete this announcement?" is displayed' do
        accept_alert('Are you sure you want to delete this announcement?') do
          page.first('.test-delete-announcement').click
        end
      end
      step 'I see a flash notice that the announcement was successfully deleted' do
        expect_flash(:notice, 'The announcement was successfully deleted')
      end
      step 'The dashboard announcement index page displays no announcement' do
        expect(page).to have_no_text(edited_announcement_text)
      end
    end
  end
end
