development:
  api_redis_host: localhost
  api_redis_port: 6379
  api_redis_timeout: 2592000 # 30 days in seconds
  api_redis_password: ''
  api_redis_enabled: false

test: &TEST
  api_redis_host: localhost
  api_redis_port: 6379
  api_redis_timeout: 2592000 # 30 days in seconds
  api_redis_password: ''
  api_redis_enabled: false

# The values for staging and live are configured by chef. Just need the
# empty hash for live here so env doesn't die when compiling local assets.
live: {}

staging: {}

qa: {}
