# S3 credentials for the avatar_service gem
access_key_id:
secret_access_key:
region:
host:
bucket_name:

# nginx proxy server credentials for the avatar_service gem
api_url:
user:
password:
purgable:
