require 'capybara/rails'
require 'capybara/rspec'
require 'rack_session_access/capybara'
require 'selenium-webdriver'
require 'selenium/devtools'
require 'socket'
require 'support/rspec_js_download_helpers'
require 'ssl/ssl_server'

# If chromedriver or chrome start failing, specify CHROMEVERBOSE=true
# from the command line to get detailed logging.
CHROMEDRIVER_LOG = File.join(ENV['TMPDIR'] || '/tmp', 'chromedriver.log').freeze

# In order to be able to run Capybara over ssl, you will need to create
# an /etc/hosts entry pointing capybara.dev.vhlcentral.com to 127.0.0.1
# The necessary self-signed cert and key are already generated and stored
# in spec/ssl/ dir.
# See https://rossta.net/blog/local-ssl-for-rails-5.html for more details
# on the config that allows ssl for capybara.

module CapybaraDns
  SSL_HOST = 'capybara.dev.vhlcentral.com'.freeze
  mattr_accessor :dns_valid

  class << self
    def validate!
      return if valid?

      warn "CONFIG ERROR: Missing required entry in /etc/hosts:\n " \
           "127.0.0.1    #{SSL_HOST}" \
           "See #{__FILE__} for more information"
      exit 1
    end

    def valid?
      # Cache the result of succcessful dns lookup so it isn't repeated
      # for every feature spec.
      return true if dns_valid

      ip_lookup = Socket.getaddrinfo(
        SSL_HOST, nil, :INET, :STREAM, nil, nil, false
      )
      # getaddrinfo returns output like:
      # [["AF_INET", 0, "localhost", "127.0.0.1", 2, 1, 6]]
      # Element at index[3] will be 127.0.0.1 if the hosts file entry
      # is set up right.
      self.dns_valid = (ip_lookup.first[3] == '127.0.0.1')
    rescue SocketError
      false
    end
  end
end

Capybara.register_server :ssl_server do |app, port, _host|
  SslServer.new.run(app, port)
end

Capybara.configure do |config|
  config.default_max_wait_time = 5
  config.app_host = "https://#{CapybaraDns::SSL_HOST}"
  config.always_include_port = true
  config.server = :ssl_server
  config.ignore_hidden_elements = false
  config.visible_text_only = true
  # Capbybara 3 does no longer match DOM Elements with text spanning over
  # multiple lines. This configuration re-enables this behavior.
  config.default_normalize_ws = true
  config.disable_animation = true
end

Capybara.server_port = 9887 + ENV['TEST_ENV_NUMBER'].to_i

def default_chrome_options
  download_path = RspecJsDownloadHelpers::PATH.to_s
  options = Selenium::WebDriver::Chrome::Options.new
  options.add_argument('ignore-certificate-errors')
  options.add_argument('use-fake-device-for-media-stream')
  options.add_argument('use-fake-ui-for-media-stream')
  options.add_argument('--unhandled-prompt-behavior=accept and notify')
  options.add_preference('download.default_directory', download_path)
  options.add_preference('profile.password_manager_leak_detection', false)
  options
end

def headless_chrome_options
  options = default_chrome_options
  options.add_argument('--headless')
  options.add_argument('--window-size=1920,1280')
  # Additional flags needed when run as root (e.g. in a Codebuild container)
  if Process.uid == 0
    options.add_argument('--no-sandbox')
    options.add_argument('--disable-dev-shm-usage')
  end
  options
end

def default_driver_args
  {
    browser: :chrome,
    options: default_chrome_options,
    service: ::Selenium::WebDriver::Service.chrome(args: chromedriver_opts)
  }
end

private def chromedriver_opts
  if ENV['CHROMEVERBOSE']
    ['--verbose', "--log-path=#{CHROMEDRIVER_LOG}"]
  else
    []
  end
end

private def assign_no_unload_flag(driver)
  # Starting at version of chrome, the unhandledPromptBehavior
  # for beforeUnload alerts is set to "accept", and cannot be overridden.
  # This makes accept_alert calls (whether making assertions about the
  # alert text or not) fail.
  # See:
  # https://www.w3.org/TR/webdriver/#user-prompt-handler
  # Assign an env var to allow feature specs that are expecting modals
  # generated by beforeunload events to stop expecting the modals.
  no_unload_version = '127.0'
  current_version = driver.browser.capabilities[:browser_version]

  if Gem::Version.new(current_version) >= Gem::Version.new(no_unload_version)
    ENV['NO_CHROME_UNLOAD'] = 'true'
  end
end

Capybara.register_driver :chrome do |app|
  driver = Capybara::Selenium::Driver.new(
    app, **default_driver_args
  )
  assign_no_unload_flag(driver)
  driver
end

Capybara.register_driver :headless_chrome do |app|
  driver = Capybara::Selenium::Driver.new(
    app, **default_driver_args.merge(options: headless_chrome_options)
  )
  assign_no_unload_flag(driver)

  if ENV['CHROMECONSOLELOG']
    driver.browser.on_log_event(:console) do |event|
      if %i[log error exception].include?(event.type)
        puts 'BROWSER CONSOLE LOG:'
        puts event.inspect
      end
    end
  end
  driver
end

Capybara.javascript_driver = if ENV['CHROMEDEBUG']
                               :chrome
                             else
                               :headless_chrome
                             end
