#!/bin/sh

set -e

echo 'CREATE DATABASE m3;' | mysql -uroot
echo "$RAILS_ENV:
  adapter: mysql2
  encoding: utf8
  reconnect: false
  database: m3
  pool: 5
  username: root
  password:
  host: localhost

gradebook_$RAILS_ENV:
  adapter: postgresql
  encoding: utf8
  database: gradebook
  pool: 1
  username: root
  password:
  host: localhost" > config/database.yml

# App can't be booted without UA_URL defined.
echo "UA_URL = 'http://localhost'" > config/initializers/local_config.rb

# App can't be booted if config/files_key.pem doesn't have an RSA key
# in it.  This is a dummy key.
echo "-----BEGIN RSA PRIVATE KEY-----
MIICXQIBAAKBgQDTb6056fGwtczLFM2I2qeCCatBdPgF2Gt0qH0toD8LaMEV52Kx
v8PyUXa1zZul90/nWCvcJgX/tSCYG8+u2eoVVp82bVrIbVfI8DB1qTJIwO3fROBs
ZDa5SwHs4sgQJlXB5QW1OuP0Zow9zUiYuMDcBakZLhkRGWmqYTEoHbelfQIDAQAB
AoGBALP0ceg/wBBZu3MBQqn/B+C6oAK3Lj2zZEnG+buyjtYEE4q0BCErCPgd875q
v9Xy9xP8zF+0ERkBLTupOAsmt35i9pw2TYYzmhLPrnuwKJeexe/qcz6BlI8BdJY4
LVIe59AUnKjH624HaxluIRlqNclcLpiSiJOi6AhUMeSxJ1UBAkEA+HndLgQ7cZ+S
u9ZRwKoyNIy7PFXDSMHDu7XaIbUqD9Pi/W3sEq95RlSwVRsyhzF/8efCZLiLkSI1
C8UYK9H0PQJBANnWsAuS6PiK15xQI1FjNk5p25OV7GsTcB5o+/kJRMAxLpv45OE7
O39FOJEEoeSWf5Yqz/fgqSr8BggcO3n7SkECQDfTCUJBaSmJ9GmHKS7kDguIYriX
fBxojBUsMinIjf6oWCMgAx3flpuag1NbnOqK0HgE3cPLQnAFA231hgyySvECQBd3
fTeB9/7uVhPMvkFCQtNnq/PWLsXKLkXYYWyOhw19Ptwmj+GDlAE9374flaEeZVgz
/HtjhFXRGIU/JVkarQECQQC+ebP9KFaQ5Q312H38LZfIiGHgQh75aYjeH8J1i/Ac
LCuCOXtm+vayM4WXYwyrPdjGhD6RNW5rot2QRNS0xIIz
-----END RSA PRIVATE KEY-----" > config/files_key.pem

# App can't be booted if the log directory doesn't exist.
mkdir -p log
echo 'TEMP: Running zeitwerk'
bundle exec rake zeitwerk:check --verbose

echo 'Precompile assets'
RAILS_GROUPS=assets time bundle exec rake assets:precompile

time bundle exec rails yarn:install

time bundle exec rails webpacker:compile

# We don't want the log directory to make it into our package.
rm -r log

# We don't need node_modules and they take up a lot of space.
rm -fr node_modules
