module Xapi
  class StatementWriter
    include AttemptUserToken

    # List of statement's attributes to save "as-is" without any transformation.
    STATEMENT_ATTRS_TO_SAVE = %i[
      object result context authority version attachments
    ].freeze
    SUBMISSION_BASE_ATTRS = {
      points_pending: 0,
      pending: false,
      submission_length: nil,
      count_attempt: true,
      gradable: true
    }.freeze
    VERB_FOR_TIME_TRACKING_STATE = {
      pause: VERB_TERMINATED,
      resume: VERB_INITIALIZED
    }.freeze

    def self.update_time_tracking(state, attempt, user, xapi_state_modifiable)
      verb = VERB_FOR_TIME_TRACKING_STATE[state]
      raise ArgumentError, "invalid state '#{state}'" unless verb

      user_token = XapiUserToken.new(
        attempt_id: attempt.id,
        user_id: user.id,
        state_modifiable: xapi_state_modifiable
      )
      params = {
        id: SecureRandom.uuid,
        actor: { mbox: user_token.mbox },
        verb: { id: verb },
        object: { objectType: Statement::OBJECT_TYPE_ACTIVITY }
      }
      StatementWriter.new(params).write
    end

    def initialize(params)
      @params = params
    end

    def write
      return true unless state_modifiable?
      # Return if the new statement has not been stored successfully.
      return false unless statement.store(attempt)

      if statement.answered?
        update_attempt_from_answered_statement
        # We just updated the submission database. Force the attempt to
        # reload the statements to be sure it also includes the last one.
        attempt.uncache_smartbook_responses
        make_submission(Smartbook::ScoreCalculator.new(attempt).points_earned)
      else
        update_attempt_from_non_answered_statement
      end
      true
    end

    private def make_submission(points_earned)
      # We do not make a submission if another process saved a new statement
      # with the verb "answered". In this case the other process will make the
      # submission with a more up to date points earned.
      # This should prevent race condition.
      # The ScoreCalculator accesses the answered statements through the
      # attempt. So we check that the number of answered statements
      # from the attempt ((including multiple submissions) ) is the same as the number in the dynamodb table.
      return unless attempt.smartbook_responses.all_answered.count == Statement.query_for_answered_count(attempt)
      submission = Gradebook::Submission.new(attempt.user, attempt.section, attempt.activity)
      submission.submit_points(submission_attrs(points_earned))
    end

    private def submission_attrs(points_earned)
      SUBMISSION_BASE_ATTRS.merge(
        {
          points_possible: attempt.activity.points_possible,
          points_earned: points_earned,
          submitted_at: Time.zone.now,
          time_spent: attempt.time_spent,
          subactivities_count: attempt.activity.question_summary_count,
          completed_subactivities_count: attempt.smartbook_responses.answered.count
        }.tap do |memo|
          memo[:partial_pending] = true if has_statement_with_response_to_instructor_graded?
        end
      )
    end

    # Return true if any statement is a response to instructor graded-interaction
    private def has_statement_with_response_to_instructor_graded?
      # Look at statements, if any statement is a response to an instructor-graded
      # interaction, add partial_pending: true to submission_attrs.
      # We don't want to turn something into partial-pending if instructor already graded.
      # So we can:
      # 1. Only look at the new statement, and set partial_pending only to true
      # 2. Look at all the statements *and* look at feedback items, and we set
      # partial_pending to true if there are statements that have no feedback_item.
      # For now, we'll implement 1.
      statement.response_to_instructor_graded_interaction?
    end

    private def statement
      @statement ||= Statement.new(
        @params.slice(*STATEMENT_ATTRS_TO_SAVE).symbolize_keys.merge(
          # https://github.com/adlnet/xAPI-Spec/blob/master/xAPI-Data.md#requirements-2
          # Statement ids MUST be generated by the LRS if a Statement is received without an id.
          id: (@params[:id] || SecureRandom.uuid),
          # https://github.com/adlnet/xAPI-Spec/blob/master/xAPI-Data.md#statement-immutability-and-exceptions
          # The "display" property of the Verb is not considered part of the Statement itself
          verb: @params[:verb][:id],
          # https://github.com/adlnet/xAPI-Spec/blob/master/xAPI-Data.md#24-statement-properties
          # Set by the LRS if not provided.
          timestamp: @params.key?(:timestamp) ? Time.parse(@params[:timestamp]) : Time.now.utc,
          # https://github.com/adlnet/xAPI-Spec/blob/master/xAPI-Data.md#248-stored
          # The time at which a Statement is stored by the LRS
          stored: Time.now.utc
        )
      )
    end

    private def calculate_time_spent
      duration_statements = Statement.query_for_duration(attempt).sort
      StatementDuration.new(duration_statements).duration
    end

    private def update_attempt_from_non_answered_statement
      # For non answered statements, we just update attempt attributes
      update_attempt_attributes(calculate_time_spent)
    end

    private def update_attempt_from_answered_statement
      # read all answered statements for this interaction, build a new Submission,
      # calculate the new points earned and write to db and gb
      time_spent = calculate_time_spent
      results = calculate_submission_database_results

      Attempt.transaction do
        # Save answered statements into submission database.
        attempt.results_datastore.write(results, Attempt::Mode::SUBMITTED)
        update_attempt_attributes(time_spent)
      end
    end

    private def update_attempt_attributes(time_spent)
      # Only update attempt attributes if they changed.
      return if attempt.status_code == new_attempt_status_code && attempt.time_spent == time_spent
      attempt.update!(
        status_code: new_attempt_status_code,
        time_spent: time_spent,
        attempt_number: 1
      )
    end

    private def new_attempt_status_code
      # There are only 3 possible attempt states: opened and submitted and completed.
      # - If the status is already completed, keep this status
      # - If we get a statement with the "answered" verb, then:
      #   - If all the questions have been answered, set the status to completed.
      #   - Else set the status to submitted.
      # - Else set the status to opened.
      # That way, a attempt that has the submitted status will never be "downgraded".
      @new_attempt_status_code ||=
        if attempt.status_code == AttemptStatus::CODE_COMPLETED
          AttemptStatus::CODE_COMPLETED
        elsif statement.verb == VERB_ANSWERED
          if all_questions_answered?
            AttemptStatus::CODE_COMPLETED
          else
            AttemptStatus::CODE_SUBMITTED
          end
        elsif attempt.status_code == AttemptStatus::CODE_SUBMITTED
          AttemptStatus::CODE_SUBMITTED
        else
          AttemptStatus::CODE_OPENED
        end
    end

    private def all_questions_answered?
      answered = Smartbook::Responses.new(answered_statements).answered.count
      total = attempt.activity.question_summary.values.sum
      answered == total
    end

    private def calculate_submission_database_results
      {
        statements: answered_statements.map { |statement| statement.attrs.to_hash }
      }
    end

    private def answered_statements
      @answered_statements ||= Statement.query_for_answered(attempt).sort
    end

    private def mbox
      @params[:actor][:mbox]
    end
  end
end
